### PR TITLE
Feature/configurable formatting

### LINKED ISSUE #28: Add formatting options (e.g. left pad)
The encoder should support common formatting needs such as left padding.

### Formatting Options

* `default` - No padding is applied to the value.
* `rightpad` - The value is padded on the right to fill available space.
* `leftpad` - The value is padded on the left to fill available space.

In all cases the value is written to the available space in a left-to-right manner. If the value length is greater than available space, the right most characters will be omitted.

### Struct Tags

The struct tag schema will be updated to support and optional third option to specify formatting – `fixed:"{startPos},{endPos},{format}"`.

### Padding Characters

| Types | Padding Character |
| ----- | ------------------- |
| `int`, `int8`, `int16`, `int32`, `int64` | `0` |
| `uint`, `uint8`, `uint16`, `uint32`, `uint64` | `0` |
| `float32`, `float64`| `0` |
| `string`, `[]byte` | `\u0020` (space)  |

Any type not listed will default to being padded with `\u0020` (space).

### PR DESCRIPTION
**Pull request by ianlopshire**
This is the first pass at configurable formatting.

Fixes #28 #36

### CODE REVIEW

**Comment by ianlopshire** [comment]
@coip, will this solve the use-case mentioned in #36?

It's not 100% to the spec in #28, but it is functional in its current state.

**Comment by coip** [comment]
> @coip, will this solve the use-case mentioned in #36?

determined friday that struct-granular padchar would support my needs, as we have some files which encode different records requiring a different padding character for distinct entry types.

this soln you've wired being struct-field granular enables the use-case I was after. 🎈

**Comment by ianlopshire** [comment]
There is additional documentation and tests I'd like to add, but this should hit master this week.

**Comment by coip** [comment]
Hmm Im experiencing unexpected behavior...
the `default` alignment tag seems to be breaking something:
https://play.golang.org/p/xG6RAaEsjv9
(Hope you dont mind the fork+release on our side, just trying to move things along where we can.)


once theres a release cut off your repo Ill update our dep pkgs to consume yours and wipe our fork.
if we find anything, Ill pursue making upstream contributions.

also, thanks tremendously for actively developing this pkg. 
let me know if there's anything specific I can contribute to get this feature rolling.

**Pull request merged**
